# Generated by Django 4.1 on 2023-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Імя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Прізвище')),
                ('username', models.CharField(blank=True, default='None', max_length=40, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
